### ISSUE TITLE
Multi site caching issue

### ISSUE THREAD

**Issue by schliesser** [TYPO3incubator/surfcamp-team-success#58]
There are caching issues across the sites with loading the right settings

**Comment by bmack** [comment]
The problem is that the dream career page does not have a dark mode toggle. And once we toggle to dark mode, this should only reflect the current site.

This is handled in global.js, but we should only worry about dark mode on a per-site basis.

Also, let's evaluate if it is sufficient if switching the CSS class is enough or if we should follow https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark

Asking @JuliaGru for help.

**Comment by JuliaGru** [comment]
@NadjaNeb fixed that issue with: https://github.com/TYPO3incubator/surfcamp-team-success/pull/53/files
